#=== Task ======
# 1_Prepare datasheet generated by Rootfly in the same format as data generated by model
# 2_Compare two dataset

# Set working directory
setwd("C:/Users/Kaining/BGU ZKN/R/MR data analysis with R/from_aotocam_to_autoanalysis/from_autocam_to_autoanalysis/2_compare pred TRL with manual")

# Load libraries
library(readxl)
library(tidyr) # make wide data long
library(xlsx) # Write data into excel
library(dplyr) # to merge dataframe

#=== Change data format from raw Rootfly data ======

# Load data
Rootfly_raw1 <- read_excel("cam3_Rootfly_every5days.xlsx") # read raw data generated by Rootfly
View(Rootfly_raw1)

# Extract desired columns by logical using grepl() function
# grepl() searches for matches to argument pattern within every item of a character vector. 
Rootfly_raw2 <- Rootfly_raw1[ , grepl("Tube|Window|Length date", colnames(Rootfly_raw1))]
View(Rootfly_raw2)

# Delete root length of session 27 since Rootfly always return one extra session
Rootfly_raw3 <- Rootfly_raw2[,-29]

Rootfly_raw3[is.na(Rootfly_raw3)] <- 0 # replace NA with 0
View(Rootfly_raw3)  

#====window1?????????,???????????????====
Rootfly_long <- gather(Rootfly_raw3, Session, Rootlength, `Length date(1)`:`Length date(26)`, factor_key=TRUE)
View(Rootfly_long)

# Load id
id <- read_excel("C:/Users/Kaining/BGU ZKN/R/MR data analysis with R/from_aotocam_to_autoanalysis/from_autocam_to_autoanalysis/1_integrate multiple files generate by model/cam3_id.xlsx", 
           sheet = "session_id")

Rootfly_long <- merge(Rootfly_long, id, by = 'Session') # Add the unique column 'DAP'
Rootfly_long <- Rootfly_long[,c("Window","Rootlength","DAP")] # keep necessary columns
View(Rootfly_long)

Rootfly_TRL <- Rootfly_long %>%
  group_by(DAP, Window) %>%  
  summarise_at(vars("Rootlength"), sum) %>% # Calculate TRL in each window 
  rename(
    Rootfly_TRL = Rootlength # rename the column since it is the TRL now
  )

View(Rootfly_TRL)

#=== Compare data analyzed by hand vs. by model =======

a <-read_excel("C:/Users/Kaining/BGU ZKN/R/MR data analysis with R/from_aotocam_to_autoanalysis/from_autocam_to_autoanalysis/1_integrate multiple files generate by model/all_pred.xlsx", 
               sheet = "sorted data with id") # Pred_TRL
b <- Rootfly_TRL

# === Alert no.1 ======
# When annotated by hand, there are windows do not contain roots throughout experiment, therefore no record exist
# However, model return TRL values form all windows
# Therefore, data from manual annotation and model estimation do not have same length
# Need to merge first, then replace NA with 0
c <- merge(a, b, by = c("Window", "DAP"), all=TRUE) # To merge two dataset together
View(c)

c[is.na(c)] <- 0 

#=== Alert no.2 ======
# When use functions write.xlsx on a data frame after it is manipulated with dplyr and 
# have the row.names option set to FALSE, I get a "Error: index out of bounds". 
# Changing the class attribute to data.frame appears to be a workaround for this issue.
attributes(a)$class <- c("data.frame") 
attributes(b)$class <- c("data.frame") 
attributes(c)$class <- c("data.frame") 

#=== write into excel
write.xlsx(a, file = "compare_pred_n_manul.xlsx", 
           sheetName="Pred_TRL", row.names = F)

write.xlsx(b, file = "compare_pred_n_manul.xlsx", 
           sheetName="Rootfly_TRL", row.names = F, append=TRUE)

write.xlsx(c, file = "compare_pred_n_manul.xlsx", 
           sheetName="Compare TRL", row.names = F, append=TRUE)
